apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:    
    matchLabels:      
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
        imagePullPolicy: IfNotPresent
        ports:
        env:
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.monitoring.enabled
          value: "false"
        - name: xpack.watcher.enabled
          value: "false"
        - name: xpack.graph.enabled
          value: "false"
        - name: xpack.ml.enabled
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        volumeMounts:
        - name: elasticsearch-logs
          mountPath: /usr/share/elasticsearch/logs
      volumes:
      - name: "elasticsearch-data"
        hostPath:
          path: /mnt/vda1/data
          type: DirectoryOrCreate
      - name: "elasticsearch-logs"
        hostPath:
          path: /mnt/vda1/logs/elasticsearch_logs
          type: DirectoryOrCreate
