apiVersion: v1
kind: Service
metadata:
  name: es-cluster
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: elasticsearch
  ports:
  - name: transport
    port: 9300
  - name: http
    port: 9200
